without using specific version

diff --git a/.github/workflows/set-stable-tag.yml b/.github/workflows/set-stable-tag.yml
--- a/.github/workflows/set-stable-tag.yml
+++ b/.github/workflows/set-stable-tag.yml
@@ -1,51 +1,42 @@
 name: Set Stable Tag
 
-on:
-  workflow_dispatch:
+on: workflow_dispatch
 
 jobs:
-  set-stable-tag-prechecks:
-    runs-on: ubuntu-latest
-    environment: Deployment
-    outputs:
-      current-version: ${{ steps.package-version.outputs.current-version }}
-    steps:
-      - uses: actions/checkout@v4
-
-      # - name: Fail if not on a release publish branch
-      #   run: |
-      #     echo "Current ref: ${{ github.ref }}"
-      #     BRANCH="${{ github.ref }}"
-      #     if [[ ! $BRANCH == refs/heads/release/*/publish ]]; then
-      #       echo "❌ This workflow can only be run on release/*/publish branches."
-      #       exit 1
-      #     fi
-
-      - name: Get NPM Version
-        id: package-version
-        uses: martinbeentjes/npm-get-version-action@v1.3.1
-
-      # - name: Validate Git tag
-      #   run: |
-      #     git fetch --tags
-      #     if [ ! $(git tag -l "v${{ steps.package-version.outputs.current-version}}") ]; then
-      #       echo "❌ Git tag does not exist" 1>&2
-      #       exit 1
-      #     fi
-
   #reusing existing workflow to run e2e tests, but on the marketplace version
   e2e-tests-on-marketplace-version:
     needs: set-stable-tag-prechecks
     uses: ./.github/workflows/product-creation-tests.yml
     with:
-      marketplace-version: ${{ needs.set-stable-tag-prepare.outputs.current-version }}
-
+      use-marketplace-version: true
 
   # set-stable-tag:
   #   runs-on: ubuntu-latest
   #   environment: Deployment
-  #   needs: [set-stable-tag-prechecks, e2e-tests-on-marketplace-version]
   #   steps:
+  #     - uses: actions/checkout@v4
+
+  #     - name: Fail if not on a release publish branch
+  #       run: |
+  #         echo "Current ref: ${{ github.ref }}"
+  #         BRANCH="${{ github.ref }}"
+  #         if [[ ! $BRANCH == refs/heads/release/*/publish ]]; then
+  #           echo "❌ This workflow can only be run on release/*/publish branches."
+  #           exit 1
+  #         fi
+
+  #     - name: Get NPM Version
+  #       id: package-version
+  #       uses: martinbeentjes/npm-get-version-action@v1.3.1
+
+  #     - name: Validate Git tag
+  #       run: |
+  #         git fetch --tags
+  #         if [ ! $(git tag -l "v${{ steps.package-version.outputs.current-version}}") ]; then
+  #           echo "❌ Git tag does not exist" 1>&2
+  #           exit 1
+  #         fi
+
   #     - name: Install SVN
   #       run: sudo apt-get install subversion -y
 
@@ -54,14 +45,14 @@ jobs:
 
   #     - name: Validate SVN tag
   #       run: |
-  #         if [ ! -d "woocommerce_svn/tags/${{ needs.set-stable-tag-prepare.outputs.current-version }}" ]; then
+  #         if [ ! -d "woocommerce_svn/tags/${{ steps.package-version.outputs.current-version}}" ]; then
   #           echo "❌ SVN tag directory does not exist" 1>&2
   #           exit 1
   #         fi
 
   #     - name: Update readme.txt
   #       env:
-  #         NEW_VERSION: ${{ needs.set-stable-tag-prepare.outputs.current-version }}
+  #         NEW_VERSION: ${{ steps.package-version.outputs.current-version}}
   #       run: |
   #         cd woocommerce_svn
   #         sed -i -E "s/^(Stable tag:)[[:space:]]*[0-9.]+/\1 $NEW_VERSION/" "trunk/readme.txt"
@@ -75,4 +66,4 @@ jobs:
   #         cat trunk/readme.txt
   #         svn status
   #         svn diff
-  #         svn commit -m "Update stable tag for version ${{ needs.set-stable-tag-prepare.outputs.current-version }}" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache --non-interactive
+  #         svn commit -m "Update stable tag for version ${{ steps.package-version.outputs.current-version}}" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache --non-interactive
